#!/sbin/runscript
# Copyright 1999-2013 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: Exp $

depend() {
	before vdr
}

start() {
	ebegin "Starting OSCam cardserver"
	start-stop-daemon --start --quiet --exec /usr/bin/oscam -- -b ${_OSCAM_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping OSCam cardserver"
	start-stop-daemon --stop --quiet --signal SIGQUIT --exec /usr/bin/oscam
	eend $?
}
