#!/sbin/runscript
# Copyright 1999-2013 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: Exp $

depend() {
	after net
	before vdr
}

start() {
	set -x
	ebegin "Starting ${DESCRIPTION}"
	start-stop-daemon --start --quiet --background --exec ${OSCAM_WD}
	eend $?
}

stop() {
	ebegin "Stopping ${DESCRIPTION}"
	kill -9 $(pidof -x ${OSCAM_WD} ${OSCAM_DAEMON}) 2>/dev/null
	eend 0
}
